### ISSUE TITLE
LDAP plus additional accounts not working

### ISSUE THREAD

**Issue by CodeShakingSheep** [toteph42/ident_switch#1]
I encounter the same bug as mentioned here: https://bitbucket.org/BoresExpress/ident_switch/issues/91/oauth2-plus-additional-accounts-not 
Can you kindly fix that?

I use OAuth2 for entering my mailbox with Roundcube. I wanted to add an additional account via this plugin to switch between accounts in one Roundcube session.

When I try switching to the second account, login fails with this error:

IMAP Error: Login failed for <username> against tls://mail.example.com from <IP address>. AUTHENTICATE XOAUTH2: A0002 NO no mechanism available in /srv/data/www/html/roundcube/program/lib/Roundcube/rcube_imap.php

Obviously, Roundcube tries to connect to this server via OAuth2, too, which has to fail. The entered password for the second account is ignored.

**Comment by toteph42** [comment]
Hi,

I'm on vacation on will take a look at beginning of June...

Florian

Am 2023-05-12 15:25, schrieb CodeShakingSheep:

> I encounter the same bug as mentioned here: 
> https://bitbucket.org/BoresExpress/ident_switch/issues/91/oauth2-plus-additional-accounts-not
> Can you kindly fix that?
> 
> I use OAuth2 for entering my mailbox with Roundcube. I wanted to add an 
> additional account via this plugin to switch between accounts in one 
> Roundcube session.
> 
> When I try switching to the second account, login fails with this 
> error:
> 
> IMAP Error: Login failed for against tls://mail.example.com from . 
> AUTHENTICATE XOAUTH2: A0002 NO no mechanism available in 
> /srv/data/www/html/roundcube/program/lib/Roundcube/rcube_imap.php
> 
> Obviously, Roundcube tries to connect to this server via OAuth2, too, 
> which has to fail. The entered password for the second account is 
> ignored.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you are subscribed to this 
> thread.Message ID: ***@***.***>


Links:
------
[1] https://github.com/toteph42/ident_switch/issues/1
[2]

**Comment by toteph42** [comment]
Hi,
did you use `oauth_login_redirect` in your RC configuration file?

**Comment by CodeShakingSheep** [comment]
Hi,
Thank you for looking into this. I use the Yunohost installation of Roundcube. You can see the `config.inc.php` file here: https://github.com/YunoHost-Apps/roundcube_ynh/blob/master/conf/config.inc.php. So, my setup doesn't use oauth but ldap (probably via imap as described here https://www.roundcubeforum.net/index.php?topic=2389.0). Sorry for the confusion.

This is the roundcube error message
`
Server Error: AUTHENTICATE PLAIN: A0003 NO Invalid login or password
`

The login data is definitely correct. I double-checked and the error is the same for all my external mail accounts I wanted to use in ident_switch. It's quite easy to reproduce. You can just install Yunohost and install Roundcube as yunohost app, install ident_switch plugin for roundcube and try to connect external mail accounts. If you need any further information please let me know. Happy to provide whatever you need.

I would be really glad if you could fix this bug :)

**Comment by toteph42** [comment]
1. Check `logs/ident_switch.log` for any hint about what went wrong.
2. Double check connection parameter. If you use `ssl`, ensure you add `ssl://` in front of your `IMAP` host name and use port `993`. for `SMTP` `ssl` port is `465` (or post your `IMAP` and `SMTP` settings).
3. On `https://dnsexit.com/it-tools/email-tools/check-imap/` you can find out more about your mail server (no need to provide `username` and/or `password`.)

**Comment by CodeShakingSheep** [comment]
Thanks for the hints.
1. There are no errors or warnings. Just `<XXXXXXX> Switching mailbox to one for identity with ID = 2 (username = 'hello@[REDACTED_DOMAIN.TLD]').`

2. Ok, I tried playing around with the connection parameters. This is what happens:
- Using TLS
`IMAP Error: Login failed for hello@[REDACTED_DOMAIN.TLD] against tls://mail.infomaniak.com from [REDACTED_IP_ADDRESS]. AUTHENTICATE PLAIN: A0003 NO Invalid login or password in /var/www/roundcube/program/lib/Roundcube/rcube_imap.php on line 211 (GET /webmail/?_task=mail&_action=getunread&_page=1&_remote=1&_unlock=0&_=1683898506281)>`
- Plain (no SSL, no TLS):
`IMAP Error: Login failed for hello@[REDACTED_DOMAIN.TLD] against mail.infomaniak.com from [REDACTED_IP_ADDRESS]. Empty startup greeting (mail.infomaniak.com:993) in /var/www/roundcube/program/lib/Roundcube/rcube_imap.php on line 211 (GET /webmail/?_task=mail&_mbox=INBOX)>`
- Using SSL
`IMAP Error: Login failed for hello@[REDACTED_DOMAIN.TLD] against ssl://mail.infomaniak.com from [REDACTED_IP_ADDRESS]. AUTHENTICATE PLAIN: A0003 NO Invalid login or password in /var/www/roundcube/program/lib/Roundcube/rcube_imap.php on line 211 (GET /webmail/?_task=mail&_action=list&_refresh=1&_layout=widescreen&_mbox=INBOX&_page=&_remote=1&_unlock=loading1686614825639&_=1686614825464)>`

3. I receive the same error message there with providing only IMAP Server Name and no login data (which I don't want to enter there).
`Error logging in. Got: 0 NO Invalid login or password`. As no login and password were provided this makes sense here, I think.

Any further suggestions?

**Comment by toteph42** [comment]
I still think it is not an `ident_switch` problem but more a configuration issue...

Try to add `$config['imap_debug'] = true;` in your `config.inc.php` and check new created file `imap.log` in roundcube log directory. 

You can finally check if `ident_switch` does not provide data if you edit `rcube_imap.php` and insert the following code at line `182`

`rcube::write_log('test', serialize($config)); `

Then you should get a new log file names `test.log` in your roundcube log directory where your login data is written (don't forget to delete file after viewing - it contains your login password).

**Comment by CodeShakingSheep** [comment]
I added `$config['imap_debug'] = true;`. This is the output in `imap.log`. Not really anything new.

```
[BA69] S: A0003 NO Invalid login or password
[60E5] S: A0003 NO Invalid login or password
[C529] Connecting to mail.infomaniak.com:993...
```
Then I modified `rcube_imap.php` as you suggested and this log gave finally brought some clarity. The problem is that the entered password in ident_switch settings is not considered. Instead the password of my ldap user with which I authenticate against localhost is used to authenticate with the external mail provider which of course can't work. However, the user (external mail address) is correctly taken into account. It's pretty strange. So, somehow there needs to be a way to tell ident_switch to use the password which was entered and not the ldap user's password. Here you can see the redacted entries from `test.log`. First line localhost which is working correctly, second line the external identity created with ident_switch.

```
a:5:{s:4:"host";s:9:"localhost";s:4:"user";s:6:"[REDACTED_LDAP_USER]";s:8:"password";s:16:"[REDACTED_LDAP_PASSWORD]";s:4:"port";i:143;s:3:"ssl";b:0;}
a:5:{s:4:"host";s:25:"tls://mail.infomaniak.com";s:4:"user";s:25:"hello@[REDACTED_DOMAIN.TLD]";s:8:"password";s:16:"[REDACTED_LDAP_PASSWORD]";s:4:"port";s:3:"993";s:3:"ssl";s:3:"tls";}
```
Do you have any idea how to fix this?

Edit: I couldn't help but shortly look into this although I'm not familiar with roundcube code base. What was striking me was [L. 164](https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube_imap.php#L164) in `rcube_imap.php`. Perhaps the password is overridden there?

**Comment by toteph42** [comment]
Ok, let's check if plugin provides correct password. Open `ident_switch.php` and add the following line

`self::write_log('Setting password "'.$rc->decrypt($r['password']).'"');`

after line 766 (`$_SESSION['password'] = $r['password'];`) and check `ident_switch.log`. 

If you do not get the password you entered in settings, the password is either wrongly stored in data base or lost during your configuration ;-).

You can also test password, by hard coding by replacing `$r['password']` with your password...

If this works, we know `roundcube` is working properly.

**Comment by CodeShakingSheep** [comment]
After adding the log statement in `ident_switch.php` and checking `ident_switch.log` I could see the correct password for the mail provider there instead of the LDAP user password.

`Setting password "[REDACTED_MAIL_PROVIDER_PASSWORD]"`

So, storing password in ident_switch seems to work correctly. So, the problem is in roundcube?

**Comment by toteph42** [comment]
Yes, it seems so. I assume password is overwritten in `rcmail_oauth.php:387`. You may check it by adding a check if password is already set `if (!isset($_SESSION['password'])` (untested).
