### ISSUE TITLE
Data is not recorded

### ISSUE THREAD

**Issue by wbiehl** [toteph42/ident_switch#4]
I installed the plugin, entered the data and activated the ident_switch. However, after saving, the data is not saved and the plugin remains disabled in the new identity created. What could I be doing wrong?

RoundCube 1.6.5
SQLite
Elastic Theme

**Comment by toteph42** [comment]
Hi [wbiehl](https://github.com/wbiehl),

I'll try to reproduce issue. Please be patient.

**Comment by toteph42** [comment]
I was able to install SQlite and test. On my test-Installation everything works fine. I used RC 1.6.6., SQlite und Elastic theme as well. Maybe you have a `log/errors.log` file which may show up, what went wrong. Please post content here.

**Comment by wbiehl** [comment]
I found these errors that may be related to my problem, especially this one about not finding the database table.

DB Error: [1] no such table: ident_switch (SQL Query: INSERT INTO ident_switch(flags, label, imap_host, imap_port, imap_delimiter, username, password, smtp_host, smtp_port, smtp_auth, user_id, iid) VALUES

PHP Warning:  Undefined array key "archive_mbox_default_iswitch" in /usr/local/lib/roundcubemail/plugins/ident_switch/ident_switch.php on line 80

PHP Error: Failed to load plugin file /usr/local/lib/roundcubemail/plugins/keyboard/keyboard.php in /usr/local/lib/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php on line 193 (GET /mail/?_task=settings&_action=identities)

**Comment by toteph42** [comment]
Seems as if installation has failed. Try removing `composer remove toteph42/ident_switch` and reinstalling `composer require totep42/ident_switch`. After installation, please check if database is available `echo .tables | sqlite3 yourdb.db`. Then you should see table `ident_switch`.

**Comment by wbiehl** [comment]
Problem resolved with reinstallation. Thank you very much!

Now there is another error. Error connecting to the SMTP server when sending an email using either of the two identities I use. Email reading occurs normally.

In SMTP Authorization I try to change it to "none" for testing, but the option is not saved.

**Comment by toteph42** [comment]
It is saved correctly - only showing wrong. Will be fixed with next version. Select none and save then you have none.
