### ISSUE TITLE
2 active tabs or notifications

### ISSUE THREAD

**Issue by artur002** [toteph42/ident_switch#6]
Is it possible to implement a function in which multiple accounts could be used in different tabs\windows? Or as an alternative: so that the drop-down list contains the number of new messages in another account, and Rouncube notifies about them, just like in the active window

**Comment by toteph42** [comment]
This is on one hand a request regarding mail notification. This currently not in scope of the plugin. I would highly appreciate if someone is willing to implement such a feature request. I do not have enough spare time to implement such a functionality. Feel free to implement yourself.

On the other hand you're request multiple tabs. Maybe you can request that feature (to open multiple tabs in Roundcube with different login data) to Roundcube core team.
