### ISSUE TITLE
Strange behavior of the "archive" folder

### ISSUE THREAD

**Issue by artur002** [toteph42/ident_switch#7]
Connected accounts (via this plugin)
1) The selected archive folder is not displayed as an archive. 2)When moving an email to the archive: the email has moved somewhere, and the operation was successful. (disappears somewhere... or is being deleted)

**Comment by artur002** [comment]
Sorry, the archive folder has been created and all emails have been moved there, but I still can't install my email folder. (settings are not applied on these accounts)

**Comment by toteph42** [comment]
Folder Management is not part of this plugin. You can check this, if you log in as the suspicious user. The plugin only overrides login data.
